import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#253457",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#3c0028",
        "secondary-fixed-dim": "#e0b6ff",
        "surface-container": "#0e1e41",
        error: "#ffb4ab",
        background: "#011134",
        "secondary-fixed": "#f2daff",
        "on-tertiary": "#620044",
        secondary: "#e0b6ff",
        "surface-container-lowest": "#000c2b",
        tertiary: "#fff4f6",
        "inverse-primary": "#006b5b",
        "primary-fixed": "#26fedc",
        "on-surface-variant": "#b9cac4",
        "surface-container-highest": "#253457",
        "on-tertiary-container": "#ad1f7d",
        "on-surface": "#dae2ff",
        "on-background": "#dae2ff",
        "outline-variant": "#3a4a46",
        "tertiary-fixed": "#ffd8e9",
        "secondary-container": "#6f00b4",
        "on-primary-fixed": "#00201a",
        "on-secondary-fixed": "#2e004e",
        surface: "#011134",
        "on-secondary": "#4b007d",
        "on-primary-fixed-variant": "#005144",
        "surface-tint": "#00dfc1",
        "surface-dim": "#011134",
        "on-tertiary-fixed-variant": "#8a0061",
        "surface-container-high": "#1a294c",
        "surface-container-low": "#091a3c",
        "primary-container": "#00f5d4",
        "tertiary-fixed-dim": "#ffafd7",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#ffcce3",
        outline: "#83948f",
        "primary-fixed-dim": "#00dfc1",
        "on-secondary-fixed-variant": "#6b00af",
        "on-primary": "#00382f",
        "on-error": "#690005",
        "inverse-on-surface": "#202f52",
        "inverse-surface": "#dae2ff",
        primary: "#d7fff3",
        "on-secondary-container": "#d7a4ff",
        "on-primary-container": "#006c5c",
        "surface-bright": "#2a385c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-expanded": "260px",
        "container-padding": "24px",
        unit: "4px",
        gutter: "16px",
        "sidebar-collapsed": "72px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
